baseURL = "https://efunopedia.netlify.com/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Efunopedia"
[[menu.footer]]
URL = "tools"
name = "Download Center"
weight = 2
[[menu.main]]
URL = "tools"
name = "Download Center"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "This is meta description"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/logo.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, Welcome to Efunopedia. <br> Let's learn and explore the new things!"
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/evan.fondx"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/evan51st"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/evan-prasetya-2017a846/"
[[params.social]]
icon = "ti-whatsapp"
link = "http://wa.me/628994983522"
